### ISSUE TITLE
Thread 1: Fatal error: {Class} is required to implement {Protocol}

### ISSUE THREAD

**Issue by kaleipdv4** [illescasDaniel/Inject-Swift#3]
Hi,

I saw the post and tried your library which I think look very promising. Unfortunately it doesn't work but I don't understand why. 
It always return the following fatal error:

Thread 1: Fatal error: {Class} is required to implement {Protocol}

But my class is already implementing the protocol. The problems seems to be happening with the demo project you provided too.

Have a nice day!

**Comment by illescasDaniel** [comment]
Solved in v1.2.2, please check it out and if it works mark this issue as solved.

I deleted those checks for now, because it seems that something about Swift changed and now they don't work as expected.

**Comment by kaleipdv4** [comment]
Good morning thank you, I just tested it now and it works as expected without the check, its just less safer of course.

Yes you are right something is weird with the types, i am thinking about it but i cant find it yet.

I have one question concerning the "add" method of the DefaultSingletonResolver. I am wondering what you mean with this comment:

"// TODO: we should avoid this when possible, but I can't cast a function to () -> Any..."

Thank you again for your prompt response!

**Comment by illescasDaniel** [comment]
That comment is from when I used "[ObjectIdentifier: Any]" internally in DefaultSingletonResolver, right now I'm using another type ([ObjectIdentifier: Lazy<Any>]) and it works fine, that comment is deprecated. (released v1.2.3 to delete this old comment and some other minor tweaks, I also updated the example project)

**Comment by illescasDaniel** [comment]
I'm closing this issue since it seems to be resolved 👍
