### ISSUE TITLE
Errors when registering dependencies/singletons, using protocols/classes defined externally

### ISSUE THREAD

**Issue by AlibZoma** [illescasDaniel/Inject-Swift#4]
Hi, thank you for making this great library Inject-Swift!

I have noticed two problems that I wanted to share.

1.

When both ServiceProtocol and Service are defined in the same app project it works fine, but if for example one of them is defined in a pod, swift package or library, it starts throwing fatal errors when resolving, and cannot locate the dependency.

For example:

```
protocol ServiceProtocol {
}
class Service: ServiceProtocol {}

DI.dependencies.add(
    ServiceProtocol.self,
    using: Service()
)

DI.dependencies.isAdded(ServiceProtocol.self) // == true
DI.dependencies.resolve(ServiceProtocol.self) // but this throws fatalError when either ServiceProtocol or Service is defined in a external library
```

`"Fatal error: You need to add ServiceProtocol to the dependency resolver"`

Maybe it has something to do with the ObjectIdentifier?

MyApp.Service

2. 

An other thing that I noticed, is that for now it doesn't seem possible to add two different class adopting a same protocol. For example:

```
protocol ServiceProtocol {
}
class ServiceA: ServiceProtocol {}
class ServiceB: ServiceProtocol {}

DI.dependencies.add(
    ServiceProtocol.self,
    using: ServiceA()
)

DI.dependencies.add(
    ServiceProtocol.self,
    using: ServiceB()
) // this will override service A
```

I think that would very good if we can register both services, because even if they implement the same protocol they are different instances. 

A workaround for us would be to register an array of protocol, or to create a more specific and unique protocol that inherits from the base protocol, but it would not be as great and moreover force unneeded changes.

I think swinject handles this with an optional "name"  when adding dependency so maybe it would be the appropriate way to do.

Thank you!

**Comment by illescasDaniel** [comment]
Hi! First of all, could you verify if this problem is still present in the latest library version? (1.2.3)

**Comment by illescasDaniel** [comment]
> for now it doesn't seem possible to add two different class adopting a same protocol

Yeah, that's how it works right now, but thanks for the tip, I might add that feature 👍🏼

**Comment by AlibZoma** [comment]
Hi, thank you for the reply @illescasDaniel !

- **For the issue**: Yes I confirm that it is happening in latest version unfortunately

- **For the multiple protocol registration**: That would really amazing if this could be added yes! I find this behaviour very useful and would add a lot to this great library

**Comment by illescasDaniel** [comment]
>  this throws fatalError when either ServiceProtocol or Service is defined in a external library

I created a dummy library in which I declared a dummy protocol, then in an app I import that dummy library and Inject. As you see, if I create a class that implements that protocol it resolves fine.

Could you verify that your Service class actually implements that specific protocol? Try printing "Service() as MyServiceProtocol". Maybe you have a class with the same name on different libraries?

<img width="2048" alt="Screenshot 2021-04-29 at 09 11 39" src="https://user-images.githubusercontent.com/17966944/116514320-26571200-a8cb-11eb-97a1-08a2f0ca287e.png">

**Comment by illescasDaniel** [comment]
@AlibZoma could you provide me with a real example of the bug? Otherwise I might close the issue.

**Comment by illescasDaniel** [comment]
As no further info has been provided I'm closing this issue for now. Feel free to open another issue if this is still happening.
